Example of non-valid transaction because of ACL violation
IBM-Blockchain/bcdb-sdk pull request #50
Opened 2021-08-24 07:43 UTC by tohar-ayash

Signed-off-by: tohar-ayash <toharayash1@gmail.com>

2021-09-19 10:50 UTC, gennadylaventman requested changes

2021-09-19 10:50 UTC, gennadylaventman commented on examples/api/acl_violation/acl_violation.go
> +	if err != nil {
First `if` may present execution of second `if`. Join both ifs together.

2021-09-19 10:50 UTC, gennadylaventman commented on examples/api/acl_violation/acl_violation.go
> +	fmt.Printf("Transaction number %s committed successfully\n", txID)
Please add at least database creation phase to separate function. In addition, you can even create utility function `addUser()` with arguments as admin session, user name, location of certificate, list of names of dbs with read only permission and list of dbs with read-write permissions.

2021-09-19 10:50 UTC, gennadylaventman commented on examples/api/acl_violation/acl_violation.go
> +	if err != nil {
Same here - first `if` prevents second `if` execution.

2021-09-26 12:16 UTC, tohar-ayash commented on examples/api/acl_violation/acl_violation.go
> +	if err != nil {
done

2021-09-26 12:17 UTC, tohar-ayash commented on examples/api/acl_violation/acl_violation.go
> +	fmt.Printf("Transaction number %s committed successfully\n", txID)
done

2021-09-26 12:17 UTC, tohar-ayash commented on examples/api/acl_violation/acl_violation.go
> +	if err != nil {
done

2021-09-26 13:05 UTC, gennadylaventman approved these changes

2021-09-26 13:05 UTC, merged