Add a method AssertRead
IBM-Blockchain/bcdb-sdk pull request #56
Opened 2021-09-14 12:03 UTC by tohar-ayash

Signed-off-by: tohar-ayash <toharayash1@gmail.com>

2021-09-19 10:10 UTC, gennadylaventman requested changes
Please add unit tests and address comments

2021-09-19 10:10 UTC, gennadylaventman commented on pkg/bcdb/data_tx_context.go
> +	dataAssert  map[string]*types.Version
dataAssert -> dataAsserts

2021-09-19 10:10 UTC, gennadylaventman commented on pkg/bcdb/data_tx_context.go
> +	ops, ok := d.operations[dbName]
Please take care of case then both `AssertRead` and `Get` executed for same key, specially take case of different versions.

2021-09-26 06:48 UTC, tohar-ayash commented on pkg/bcdb/data_tx_context.go
> +	ops, ok := d.operations[dbName]
done

2021-09-26 06:49 UTC, tohar-ayash commented on pkg/bcdb/data_tx_context.go
> +	dataAssert  map[string]*types.Version
done

2021-09-30 10:46 UTC, tock-ibm commented on pkg/bcdb/data_tx_context_test.go
> +	_, metaData, err := tx2.Get("bdb", "key1")
The metadata used in `tx2` should be from another tx, not read in the tx2 itself... in fact I think it should be an error to read a key (which records its version) and then assert on it again.... and vice versa. 

In addition, if the TX has no write set, which is legal, but weird in this context.

2021-09-30 10:46 UTC, tock-ibm commented on pkg/bcdb/data_tx_context_test.go
> +	require.NoError(t, err)
If you are asserting the wrong value the TX should fail, no?

2021-09-30 10:46 UTC, tock-ibm commented on pkg/bcdb/data_tx_context_test.go
> +func TestDataContext_AssertRead(t *testing.T){
test also assert on the zero version, i.e. assert the non-existence of a value.

2021-09-30 10:46 UTC, tock-ibm commented on pkg/bcdb/data_tx_context.go
> +		}
you must ensure that the keys from dataAsserts and dataReads are mutually exclusive.
This can be done in the `AssertRead` and `Get` operations, respectively.

2021-09-30 10:46 UTC, tock-ibm commented on pkg/bcdb/data_tx_context.go
> +		}
I would argue, for simplicity, that:

- If you had done a `Get`, you can not do an `AssertRead` on the same key.
- If you had done an `AssertRead` you cannot do a `Get` at all (you have to change the code for Get).

because that would constitute a programming error.

2021-10-03 14:32 UTC, tohar-ayash commented on pkg/bcdb/data_tx_context.go
> +		}
done

2021-10-03 14:38 UTC, tohar-ayash commented on pkg/bcdb/data_tx_context_test.go
> +	_, metaData, err := tx2.Get("bdb", "key1")
done

2021-10-03 14:39 UTC, tohar-ayash commented on pkg/bcdb/data_tx_context.go
> +		}
done

2021-10-03 14:39 UTC, tohar-ayash commented on pkg/bcdb/data_tx_context.go
> +		}
done

2021-10-04 10:42 UTC, tock-ibm commented on pkg/bcdb/data_tx_context.go
> +		}
Check that the new version is equal to the existing, else fail it. No need for a named error object here, just and error with `errors.Errorf(...)`.

2021-10-04 10:42 UTC, tock-ibm commented on pkg/bcdb/data_tx_context.go
> +			return &ErrorGetAndAssertReadForTheSameKey{Key: key}
No need for a named error object here, just an error with `errors.Errorf(...)`. We need a named error object only when we expect the user to match against the error type and do something specific... I don't think this is the case here.

2021-10-04 10:42 UTC, tock-ibm commented on pkg/bcdb/data_tx_context.go
> +			return nil, nil, &ErrorGetAndAssertReadForTheSameKey{Key: key}
No need for a named error object here, just an error with `errors.Errorf(...)`. We need a named error object only when we expect the user to match against the error type and do something specific... I don't think this is the case here.

2021-10-04 10:42 UTC, tock-ibm commented on pkg/bcdb/data_tx_context_test.go
> +	require.NoError(t, err)
Add another check that verifies that with a nil or empty version the commit fails when the key exists.

2021-10-04 10:42 UTC, tock-ibm commented on pkg/bcdb/data_tx_context_test.go
> +	for i := 0; i < 1000; i++ {
I would argue that the loop could start before line 390 (`tx3, err := adminSession.DataTx()`), and end after line 408 (after commit). This way we have 1000 different TXs, all using the same AssertRead version.

2021-10-04 10:42 UTC, tock-ibm commented
Overall looks good, just a few minor comments.

2021-10-04 13:17 UTC, tohar-ayash commented on pkg/bcdb/data_tx_context.go
> +		}
done

2021-10-04 13:17 UTC, tohar-ayash commented on pkg/bcdb/data_tx_context_test.go
> +	require.NoError(t, err)
done

2021-10-04 13:17 UTC, tohar-ayash commented on pkg/bcdb/data_tx_context_test.go
> +	for i := 0; i < 1000; i++ {
done

2021-10-04 13:43 UTC, tock-ibm approved these changes

2021-10-04 13:44 UTC, merged